### ISSUE TITLE
Error using Construct 2 Cordova export and Phonegap build

### ISSUE THREAD

**Issue by andersonhorita** [cranberrygame/cordova-plugin-ad-admob#29]
I'm getting this error:
_:compileArmv7ReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/com/cranberrygame/cordova/plugin/ad/admob/AdMobOverlap.java:576: error: AdMobOverlap.MyRewardedVideoListener is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
	class MyRewardedVideoListener implements RewardedVideoAdListener {_

The full log is bellow:

```
Build Date: 2018-06-01 19:16:49 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-android-support-gradle-release" via npm
Installing "cordova-android-support-gradle-release" at "1.4.3" for android
Subproject Path: CordovaLib
Fetching plugin "cordova-custom-config" via npm
Installing "cordova-custom-config" at "5.0.2" for android
Fetching plugin "cordova-plugin-ad-admob" via npm
Installing "cordova-plugin-ad-admob" at "1.0.118" for android
Fetching plugin "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" via git clone
Using shallow clone
Repository "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" checked out to git ref "master" at "b22949d".
Installing "cordova-plugin-ad-admob-sdk" at "1.0.36" for android
Fetching plugin "https://github.com/cranberrygame/cordova-plugin-extras-google-play-services" via git clone
Using shallow clone
Repository "https://github.com/cranberrygame/cordova-plugin-extras-google-play-services" checked out to git ref "master" at "f6f6b28".
Installing "cordova-plugin-extras-google-play-services" at "1.0.5" for android
Subproject Path: CordovaLib
Fetching plugin "cordova-plugin-crosswalk-webview" via npm
Installing "cordova-plugin-crosswalk-webview" at "2.4.0" for android
Subproject Path: CordovaLib

        After much discussion and analysis of the market, we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.

        So the minSdkVersion of Cordova project is configured to 16 by default.
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "3.0.0" for android
Fetching plugin "cordova-plugin-statusbar" via npm
Installing "cordova-plugin-statusbar" at "2.4.2" for android
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
WARNING: Overriding compileSdkVersion from android-25 (default) to android-26
WARNING: This is unsupported, please consider updating your phonegap version instead
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.gradle.include.1=cordova-android-support-gradle-release/tcb1000r-cordova-android-support-gradle-release.gradle
cordova.system.library.1=com.google.android.gms:play-services-games:+
cordova.system.library.2=com.google.android.gms:play-services-plus:+
cordova.system.library.3=com.google.android.gms:play-services-ads:+
cordova.gradle.include.2=cordova-plugin-crosswalk-webview/tcb1000r-xwalk.gradle
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Subproject Path: CordovaLib
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------
null
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_26hrjtivihs2ywqx5z7tmx902.run(/project/build.gradle:139)
org.xwalk:xwalk_core_library:23+
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
:preBuild UP-TO-DATE
:preArmv7ReleaseBuild UP-TO-DATE
:checkArmv7ReleaseManifest
:preArmv7DebugBuild UP-TO-DATE
:preX86DebugBuild UP-TO-DATE
:preX86ReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareAndroidArchCoreRuntime110Library
:prepareAndroidArchLifecycleLivedataCore110Library
:prepareAndroidArchLifecycleRuntime110Library
:prepareAndroidArchLifecycleViewmodel110Library
:prepareComAndroidSupportCustomtabs2711Library
:prepareComAndroidSupportSupportCompat2711Library
:prepareComAndroidSupportSupportCoreUi2711Library
:prepareComAndroidSupportSupportCoreUtils2711Library
:prepareComAndroidSupportSupportFragment2711Library
:prepareComAndroidSupportSupportMediaCompat2711Library
:prepareComAndroidSupportSupportV42711Library
:prepareComGoogleAndroidGmsPlayServicesAds1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsBase1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1501Library
:prepareComGoogleAndroidGmsPlayServicesAudience1501Library
:prepareComGoogleAndroidGmsPlayServicesBase1501Library
:prepareComGoogleAndroidGmsPlayServicesBasement1501Library
:prepareComGoogleAndroidGmsPlayServicesDrive1501Library
:prepareComGoogleAndroidGmsPlayServicesGames1501Library
:prepareComGoogleAndroidGmsPlayServicesGass1501Library
:prepareComGoogleAndroidGmsPlayServicesPlus1501Library
:prepareComGoogleAndroidGmsPlayServicesTasks1501Library
:prepareOrgXwalkXwalk_core_library23535894Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareArmv7ReleaseDependencies
:compileArmv7ReleaseAidl
:compileArmv7ReleaseRenderscript
:generateArmv7ReleaseBuildConfig
:mergeArmv7ReleaseShaders
:compileArmv7ReleaseShaders
:generateArmv7ReleaseAssets
:mergeArmv7ReleaseAssets
:createXwalkCommandLineFileArmv7Release
:generateArmv7ReleaseResValues
:generateArmv7ReleaseResources
:mergeArmv7ReleaseResources
:processArmv7ReleaseManifest
:processArmv7ReleaseResources
:generateArmv7ReleaseSources
:incrementalArmv7ReleaseJavaCompilationSafeguard
:compileArmv7ReleaseJavaWithJavac
:compileArmv7ReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/com/cranberrygame/cordova/plugin/ad/admob/AdMobOverlap.java:576: error: AdMobOverlap.MyRewardedVideoListener is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
	class MyRewardedVideoListener implements RewardedVideoAdListener {
	^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:compileArmv7ReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7ReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.34 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/src/com/cranberrygame/cordova/plugin/ad/admob/AdMobOverlap.java:576: error: AdMobOverlap.MyRewardedVideoListener is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
	class MyRewardedVideoListener implements RewardedVideoAdListener {
	^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7ReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by hungdt-ibl** [comment]
https://github.com/cranberrygame/cordova-plugin-ad-admob/pull/30/files
seen it missing abstract method

**Comment by Awi20** [comment]
I got same problem today, is anyone can tell me how to fix it?
