### ISSUE TITLE
Failed to install plugin 'cordova-plugin-ad-admob'

### ISSUE THREAD

**Issue by singhkamall** [cranberrygame/cordova-plugin-ad-admob#33]
I tried with command: 
**cordova prepare**
and it give following error-

Installing "cordova-plugin-ad-admob" for android
Failed to install 'cordova-plugin-ad-admob': CordovaError: Failed to fetch plugin https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\Owner\AppData\Local\Temp\npm-62588-f5ad9b05\git-cache-1a32a472\b22949df24ccf9b5e3c743b7afde904a93d7f890
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" "--production" "--no-save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Owner\Desktop\Sumo Saga\npm-debug.log
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Failed to restore plugin "cordova-plugin-ad-admob" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\Owner\AppData\Local\Temp\npm-62588-f5ad9b05\git-cache-1a32a472\b22949df24ccf9b5e3c743b7afde904a93d7f890
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" "--production" "--no-save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Owner\Desktop\Sumo Saga\npm-debug.log

When I trid with command:
**cordova plugin add https://github.com/cranberrygame/cordova-plugin-ad-admob**
It give following error-

Installing "cordova-plugin-ad-admob" for android
Failed to install 'cordova-plugin-ad-admob': CordovaError: Failed to fetch plugin https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\Owner\AppData\Local\Temp\npm-60332-b7b74804\git-cache-d3779186\b22949df24ccf9b5e3c743b7afde904a93d7f890
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" "--production" "--save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Owner\Desktop\Sumo Saga\npm-debug.log
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(node:61700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to fetch plugin https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\Owner\AppData\Local\Temp\npm-60332-b7b74804\git-cache-d3779186\b22949df24ccf9b5e3c743b7afde904a93d7f890
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" "--production" "--save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Owner\Desktop\Sumo Saga\npm-debug.log

How can I install it correctly?

**Comment by eddienk** [comment]
same here :(

**Comment by Nightmaredd** [comment]
Got the same issue, anyone know how to fix it?

**Comment by JoaquimPM** [comment]
Hi!

I have the same isue.
Did you solve this problem?
Does anyone know how to solve this?

**Comment by MarceloGh05t** [comment]
if you try to install via github it is this error, to fix just install via nmp. type the command below:
npm i cordova-plugin-ad-admo

**Comment by MarceloGh05t** [comment]
> Hi!
> 
> I have the same isue.
> Did you solve this problem?
> Does anyone know how to solve this?

if you try to install via github it is this error, to fix just install via nmp. type the command below:
npm i cordova-plugin-ad-admo

**Comment by MarceloGh05t** [comment]
> I tried with command:
> **cordova prepare**
> and it give following error-
> 
> Installing "cordova-plugin-ad-admob" for android
> Failed to install 'cordova-plugin-ad-admob': CordovaError: Failed to fetch plugin https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: cmd: Command failed with exit code 4294963228 Error output:
> npm ERR! addLocal Could not install C:\Users\Owner\AppData\Local\Temp\npm-62588-f5ad9b05\git-cache-1a32a472\b22949df24ccf9b5e3c743b7afde904a93d7f890
> npm ERR! Windows_NT 10.0.17134
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" "--production" "--no-save"
> npm ERR! node v6.11.3
> npm ERR! npm v3.10.10
> npm ERR! code EISDIR
> npm ERR! errno -4068
> npm ERR! syscall read
> 
> npm ERR! eisdir EISDIR: illegal operation on a directory, read
> npm ERR! eisdir This is most likely not a problem with npm itself
> npm ERR! eisdir and is related to npm not being able to find a package.json in
> npm ERR! eisdir a package you are trying to install.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! C:\Users\Owner\Desktop\Sumo Saga\npm-debug.log
> at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
> at _rejected (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
> at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
> at Promise.when (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
> at Promise.promise.promiseDispatch (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
> at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
> at runSingle (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
> at flush (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
> at _combinedTickCallback (internal/process/next_tick.js:73:7)
> at process._tickCallback (internal/process/next_tick.js:104:9)
> Failed to restore plugin "cordova-plugin-ad-admob" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: cmd: Command failed with exit code 4294963228 Error output:
> npm ERR! addLocal Could not install C:\Users\Owner\AppData\Local\Temp\npm-62588-f5ad9b05\git-cache-1a32a472\b22949df24ccf9b5e3c743b7afde904a93d7f890
> npm ERR! Windows_NT 10.0.17134
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" "--production" "--no-save"
> npm ERR! node v6.11.3
> npm ERR! npm v3.10.10
> npm ERR! code EISDIR
> npm ERR! errno -4068
> npm ERR! syscall read
> 
> npm ERR! eisdir EISDIR: illegal operation on a directory, read
> npm ERR! eisdir This is most likely not a problem with npm itself
> npm ERR! eisdir and is related to npm not being able to find a package.json in
> npm ERR! eisdir a package you are trying to install.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! C:\Users\Owner\Desktop\Sumo Saga\npm-debug.log
> 
> When I trid with command:
> **cordova plugin add https://github.com/cranberrygame/cordova-plugin-ad-admob**
> It give following error-
> 
> Installing "cordova-plugin-ad-admob" for android
> Failed to install 'cordova-plugin-ad-admob': CordovaError: Failed to fetch plugin https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: cmd: Command failed with exit code 4294963228 Error output:
> npm ERR! addLocal Could not install C:\Users\Owner\AppData\Local\Temp\npm-60332-b7b74804\git-cache-d3779186\b22949df24ccf9b5e3c743b7afde904a93d7f890
> npm ERR! Windows_NT 10.0.17134
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" "--production" "--save"
> npm ERR! node v6.11.3
> npm ERR! npm v3.10.10
> npm ERR! code EISDIR
> npm ERR! errno -4068
> npm ERR! syscall read
> 
> npm ERR! eisdir EISDIR: illegal operation on a directory, read
> npm ERR! eisdir This is most likely not a problem with npm itself
> npm ERR! eisdir and is related to npm not being able to find a package.json in
> npm ERR! eisdir a package you are trying to install.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! C:\Users\Owner\Desktop\Sumo Saga\npm-debug.log
> at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
> at _rejected (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
> at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
> at Promise.when (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
> at Promise.promise.promiseDispatch (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
> at C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
> at runSingle (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
> at flush (C:\Users\Owner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
> at _combinedTickCallback (internal/process/next_tick.js:73:7)
> at process._tickCallback (internal/process/next_tick.js:104:9)
> (node:61700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to fetch plugin https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: cmd: Command failed with exit code 4294963228 Error output:
> npm ERR! addLocal Could not install C:\Users\Owner\AppData\Local\Temp\npm-60332-b7b74804\git-cache-d3779186\b22949df24ccf9b5e3c743b7afde904a93d7f890
> npm ERR! Windows_NT 10.0.17134
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "https://github.com/cranberrygame/cordova-plugin-ad-admob-sdk" "--production" "--save"
> npm ERR! node v6.11.3
> npm ERR! npm v3.10.10
> npm ERR! code EISDIR
> npm ERR! errno -4068
> npm ERR! syscall read
> 
> npm ERR! eisdir EISDIR: illegal operation on a directory, read
> npm ERR! eisdir This is most likely not a problem with npm itself
> npm ERR! eisdir and is related to npm not being able to find a package.json in
> npm ERR! eisdir a package you are trying to install.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! C:\Users\Owner\Desktop\Sumo Saga\npm-debug.log
> 
> How can I install it correctly?

if you try to install via github it is this error, to fix just install via nmp. type the command below:
npm i cordova-plugin-ad-admo
